
# This file was *autogenerated* from the file variables.sage
from sage.all_cmdline import *   # import sage library

class VariableGenerator(object): 
     def __init__(self, prefix): 
         self.__prefix = prefix 
     @cached_method 
     def __getitem__(self, key): 
         return SR.var("%s%s"%(self.__prefix,key)) 


